import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import { WhatsAppCta } from "@/components/ui/whatsapp-cta";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gaId = process.env.NEXT_PUBLIC_GA_ID;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <WhatsAppCta source="floating_cta" />
      </body>
      {/*
        O <GoogleAnalytics> do @next/third-parties carrega o script via
        next/script (estratégia afterInteractive): se o script for bloqueado
        por um ad-blocker ou falhar ao carregar, isso não afeta o render do
        <body> acima nem lança erro — apenas o rastreamento fica indisponível
        (FR-011). Sem NEXT_PUBLIC_GA_ID definido, o componente nem é montado.
      */}
      {gaId ? <GoogleAnalytics gaId={gaId} /> : null}
    </html>
  );
}
